### ISSUE TITLE
Select statement broken on options longer than 1 token

### ISSUE THREAD

**Issue by johanrosenkilde** [microsoft/guidance#16]
I suspect that the `select` statement is broken whenever some the options are longer than 1 token, due to a misunderstanding of how `top_logprobs` work. The crucial property is that the `i`th entry of `top_logprobs` contains the top logprobs _assuming that the `i-1` first tokens are as in the returned completion_. 

To exemplify the problem, say that your select has two options `YesNo` and `NoYes` for strange reasons. These are both 2 tokens and consist of tokens `Yes` and `No`, so those are the only ones biased to be output by the model. They're both weird, though, and it's much more likely that the model returns e.g. `YesYes`. So let's say it does.

What your select statement then *should* be computing is:
* `logprob(YesNo)`: The logprob of first generating `Yes` plus _then_ generating `No`.
* `logprob(NoYes)`: The logprob of first generating `No` plus _then_ generating `Yes`.

Your code gets the first one right. But for point two, what you're computing is rather:

* `X`: The logprob of first generating `No`, plus the logprob of generating `Yes` after first generating `Yes`.

It's unclear how `X` will compare to the true `logprob(NoYes)`, but the end result is that what gets selected has little relation to what the model truly finds most probably.

Note that the problem compounds the longer the options are.

**Comment by slundberg** [comment]
@johanrosenkilde thank you so much for pointing that out! I was just trying to clean up the select statement implementation yesterday, and you are right, it is off right now.

The plan (which I will now move up to today) will be to instead call the model just for single decision tokens, since those are the branch points in the flow of the prompt. That will be faster (especially for local models), and avoid the issue you raise here.

I'll post back here when that is pushed.

**Comment by slundberg** [comment]
This is now fixed as of 0.0.46. We now recursively parse the select like a decision tree at each point where the tokens diverge. We also now force valid outcomes via logit bias on both transformers and openAI endpoints. Thanks again!
